update example docs to match tests
cypress-io/cypress-example-kitchensink pull request #807
Opened 2024-03-14 21:40 UTC by rubysolo

Fixes #804

2024-03-14 21:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress-example-kitchensink?pullRequest=807) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress-example-kitchensink?pullRequest=807) before we can accept your contribution.<br/><hr/>**Solomon White** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress-example-kitchensink?pullRequest=807) it.</sub>

2024-03-15 10:03 UTC, MikeMcC399 commented on app/commands/misc.html
> -  cy.contains('Cheryl').click().end()
Removing `.end()` makes this example no longer meaningful.

2024-03-15 10:05 UTC, MikeMcC399 commented on cypress/e2e/2-advanced-examples/misc.cy.js
> -      //.end()
same here

2024-03-16 11:13 UTC, MikeMcC399 requested changes
This PR needs to use semantic commit
`fix:` not `chore:` in order to generate and release a new version for upstream https://github.com/cypress-io/cypress/tree/develop/packages/example to deploy the updated app contents to https://example.cypress.io/

2024-03-20 15:17 UTC, MikeMcC399 commented
- This PR is also suffering from the issue https://github.com/cypress-io/cypress/issues/29172 causing CircleCI tests to fail on Firefox.

2024-03-25 11:06 UTC, MikeMcC399 commented
@rubysolo 

- PR https://github.com/cypress-io/cypress-example-kitchensink/pull/813 needs to be merged to get the Firefox tests to pass.
- I also made a suggestion in https://github.com/cypress-io/cypress-documentation/issues/5752#issuecomment-2010182850 about possibly using `log.end()` as a replacement example. There hasn't been any feedback on that yet.

2024-03-28 12:24 UTC, MikeMcC399 requested changes
`end` has not been removed everywhere:

![image](https://github.com/cypress-io/cypress-example-kitchensink/assets/66998419/f8f50d08-d06f-4047-96cb-f00ed4e3ba82)

https://github.com/rubysolo/cypress-example-kitchensink/blob/9c9ffeb72097b578d699d92a58d2964d5aeb33b9/app/index.html#L179
```html
              <li><a href="/commands/misc">end</a></li>
```

2024-03-28 14:57 UTC, jennifer-shehane approved these changes

2024-03-28 15:01 UTC, MikeMcC399 approved these changes
LGTM! 
Good work @rubysolo !

2024-03-28 18:54 UTC, merged